# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(861, 706)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.labelRemainTime = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelRemainTime.setFont(font)
        self.labelRemainTime.setObjectName("labelRemainTime")
        self.horizontalLayout_3.addWidget(self.labelRemainTime)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditContact = QtWidgets.QLineEdit(Form)
        self.lineEditContact.setObjectName("lineEditContact")
        self.horizontalLayout.addWidget(self.lineEditContact)
        self.buttonContact = QtWidgets.QPushButton(Form)
        self.buttonContact.setObjectName("buttonContact")
        self.horizontalLayout.addWidget(self.buttonContact)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(300, 380))
        self.label_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../ScriptGithub/MyWechat/src/alipay.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(300, 380))
        self.label_6.setMaximumSize(QtCore.QSize(300, 380))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../ScriptGithub/MyWechat/src/wechatpay.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "微信消息自动发送"))
        self.label_4.setText(_translate("Form", "微信消息自动发送 (V.1.2)"))
        self.label_2.setText(_translate("Form", "1.请确保已经打开PC端微信窗口；\n"
"2.通讯录json文件已正确编辑，每个人在您的通讯录中唯一；\n"
"3.点击发送消息后，有10秒钟时间手动点击微信窗口，并令其至于最前，全部消息发送完毕前，请误操作电脑，\n"
"  之至出现发送完毕的对话框。"))
        self.labelRemainTime.setText(_translate("Form", "激活微信剩余时间：\n"
"10s"))
        self.label.setText(_translate("Form", "通讯录文件路径"))
        self.buttonContact.setText(_translate("Form", "浏览"))
        self.pushButton.setText(_translate("Form", "发送消息"))
        self.label_3.setText(_translate("Form", "此项目开源免费，如果能够在逢年过节期间帮到您，欢迎请我喝咖啡。"))
